dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-7

before_script:
  - export CXX=g++-7
  - g++ -v
  - cmake --version
  - mkdir -p build

script:
  - cd build/
  - cmake ..
  - make
  - make test
  - cd ..