dist: trusty
language: cpp

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-7
      - g++-7

script:
  - export CC=gcc-7
  - export CXX=g++-7
  - g++ -v
  - cmake --version
  - mkdir build
  - cd build/
  - cmake ..
  - make